version: '3'
volumes:
  mongo-data:
services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    network_mode: host
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
